"""Add language, segments, and summary models

Revision ID: 61b0338b2c08
Revises: b64d5e92858b, f4c2e9a7b1d0
Create Date: 2026-09-08 18:22:46.334146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b0338b2c08'
down_revision: Union[str, Sequence[str], None] = (
    'b64d5e92858b',
    'f4c2e9a7b1d0',
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    summary_created = False
    if "summaries" not in tables:
        op.create_table(
            "summaries",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("short_summary", sa.Text(), nullable=True),
            sa.Column("detailed_summary", sa.Text(), nullable=True),
            sa.Column("status", sa.Enum("NOT_STARTED", "PROCESSING", "COMPLETED", "FAILED", name="summarystatus"), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
            sa.Column("updated_at", sa.DateTime(timezone=True)),
            sa.Column("transcript_id", sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(["transcript_id"], ["transcripts.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("transcript_id"),
        )
        op.create_index("ix_summaries_id", "summaries", ["id"])
        summary_created = True

    summary_columns = set() if summary_created else {column["name"] for column in inspector.get_columns("summaries")}
    transcript_columns = {column["name"] for column in inspector.get_columns("transcripts")}
    moment_columns = {column["name"] for column in inspector.get_columns("key_moments")}

    if not summary_created and "short_summary" not in summary_columns:
        op.add_column("summaries", sa.Column("short_summary", sa.Text(), nullable=True))
    if not summary_created and "detailed_summary" not in summary_columns:
        op.add_column("summaries", sa.Column("detailed_summary", sa.Text(), nullable=True))
    if not summary_created and "transcript_id" not in summary_columns:
        op.add_column("summaries", sa.Column("transcript_id", sa.Uuid(), nullable=True))
        op.execute(
            "UPDATE summaries SET transcript_id = transcripts.id "
            "FROM transcripts WHERE summaries.video_id = transcripts.video_id"
        )
        op.alter_column("summaries", "transcript_id", nullable=False)
    if not summary_created and "content" in summary_columns:
        op.execute("UPDATE summaries SET short_summary = COALESCE(short_summary, content)")
    if not summary_created and "overview" in summary_columns:
        op.execute("UPDATE summaries SET detailed_summary = COALESCE(detailed_summary, overview)")

    if not summary_created:
        constraints = {constraint["name"] for constraint in inspector.get_unique_constraints("summaries")}
        if "summaries_transcript_id_key" not in constraints:
            op.create_unique_constraint("summaries_transcript_id_key", "summaries", ["transcript_id"])
        foreign_keys = {foreign_key["name"] for foreign_key in inspector.get_foreign_keys("summaries")}
        if "summaries_transcript_id_fkey" not in foreign_keys:
            op.create_foreign_key("summaries_transcript_id_fkey", "summaries", "transcripts", ["transcript_id"], ["id"])

    if "language" not in transcript_columns:
        op.add_column("transcripts", sa.Column("language", sa.String(length=10), nullable=True))
    if "segments" not in transcript_columns:
        op.add_column("transcripts", sa.Column("segments", sa.JSON(), nullable=True))

    if "text" not in moment_columns and "description" in moment_columns:
        op.alter_column("key_moments", "description", new_column_name="text")
    if "highlight_path" not in moment_columns:
        op.add_column("key_moments", sa.Column("highlight_path", sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'segments')
    op.drop_column('transcripts', 'language')
    op.create_table('key_moments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('importance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('highlight_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('key_moments_video_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('key_moments_pkey'))
    )
    op.create_index(op.f('ix_key_moments_video_id'), 'key_moments', ['video_id'], unique=False)
    op.create_index(op.f('ix_key_moments_id'), 'key_moments', ['id'], unique=False)
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
