"""Add language, segments, and summary models

Revision ID: 61b0338b2c08
Revises: 
Create Date: 2026-09-08 18:22:46.334146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b0338b2c08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='summarystatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id')
    )
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    op.drop_index(op.f('ix_key_moments_id'), table_name='key_moments')
    op.drop_index(op.f('ix_key_moments_video_id'), table_name='key_moments')
    op.drop_table('key_moments')
    op.add_column('transcripts', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('transcripts', sa.Column('segments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'segments')
    op.drop_column('transcripts', 'language')
    op.create_table('key_moments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('importance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('highlight_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('key_moments_video_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('key_moments_pkey'))
    )
    op.create_index(op.f('ix_key_moments_video_id'), 'key_moments', ['video_id'], unique=False)
    op.create_index(op.f('ix_key_moments_id'), 'key_moments', ['id'], unique=False)
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
