"""add transcripts and key moments tables

Revision ID: 77f8dc1412bc
Revises: 89b856a8da67
Create Date: 2026-09-04 09:51:50.456276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f8dc1412bc'
down_revision: Union[str, Sequence[str], None] = '89b856a8da67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    # op.drop_table('transcripts')
    op.drop_index(op.f('ix_key_moments_video_id'), table_name='key_moments')
    op.drop_index(op.f('ix_key_moments_id'), table_name='key_moments')
    # op.drop_table('key_moments')
    # ### end Alembic commands ###
