"""add transcripts and key moments tables

Revision ID: 77f8dc1412bc
Revises: 89b856a8da67
Create Date: 2026-09-04 09:51:50.456276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f8dc1412bc'
down_revision: Union[str, Sequence[str], None] = '89b856a8da67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = sa.inspect(op.get_bind())
    tables = inspector.get_table_names()

    if "key_moments" not in tables:
        op.create_table(
            "key_moments",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("video_id", sa.Uuid(), nullable=False),
            sa.Column("start_time", sa.Float(), nullable=False),
            sa.Column("end_time", sa.Float(), nullable=False),
            sa.Column("title", sa.String(), nullable=False),
            sa.Column("topic", sa.String(), nullable=True),
            sa.Column("importance_score", sa.Float(), nullable=False),
            sa.Column("text", sa.Text(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
            sa.ForeignKeyConstraint(["video_id"], ["videos.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_key_moments_id", "key_moments", ["id"])
        op.create_index("ix_key_moments_video_id", "key_moments", ["video_id"])

    if "transcripts" not in tables:
        op.create_table(
            "transcripts",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("text", sa.Text(), nullable=True),
            sa.Column(
                "status",
                sa.Enum("PENDING", "NOT_STARTED", "PROCESSING", "COMPLETED", "FAILED", name="transcript_status"),
                nullable=False,
            ),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
            sa.Column("updated_at", sa.DateTime(timezone=True)),
            sa.Column("video_id", sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(["video_id"], ["videos.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("video_id"),
        )
        op.create_index("ix_transcripts_id", "transcripts", ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_key_moments_video_id'), table_name='key_moments')
    op.drop_index(op.f('ix_key_moments_id'), table_name='key_moments')
    op.drop_table('key_moments')
    # ### end Alembic commands ###
