"""add highlight path to key moments

Revision ID: b64d5e92858b
Revises: 77f8dc1412bc
Create Date: 2026-09-04 15:04:03.955660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64d5e92858b'
down_revision: Union[str, Sequence[str], None] = '77f8dc1412bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_moments', sa.Column('highlight_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_moments', 'highlight_path')
    # ### end Alembic commands ###
